#ifndef _MATCHASEQ_SYMS
#define _MATCHASEQ_SYMS
#define SEQ_A1 KC_1
#define SEQ_A2 KC_2
#define SEQ_A3 KC_3
#define SEQ_A4 KC_4
#define SEQ_A5 KC_5
#define SEQ_A6 KC_6
#define SEQ_A7 KC_7
#define SEQ_A8 KC_8
#define SEQ_A9 KC_9
#define SEQ_A10 KC_0
#define SEQ_A11 KC_MINUS
#define SEQ_A12 KC_EQUAL
#define SEQ_A13 KC_BACKSPACE
#define SEQ_A14 KC_TAB
#define SEQ_A15 KC_GRAVE
#define SEQ_A16 KC_ESCAPE
#define SEQ_B1 KC_Q
#define SEQ_B2 KC_W
#define SEQ_B3 KC_E
#define SEQ_B4 KC_R
#define SEQ_B5 KC_T
#define SEQ_B6 KC_Y
#define SEQ_B7 KC_U
#define SEQ_B8 KC_I
#define SEQ_B9 KC_O
#define SEQ_B10 KC_P
#define SEQ_B11 KC_LBRACKET
#define SEQ_B12 KC_RBRACKET
#define SEQ_B13 KC_BACKSLASH
#define SEQ_B14 KC_A
#define SEQ_B15 KC_S
#define SEQ_B16 KC_D
#define SEQ_BANK KC_F1
#define SEQ_BPM KC_F2
#define SEQ_COPY KC_F3
#define SEQ_DIV KC_F4
#define SEQ_LAST KC_F5
#define SEQ_MODE KC_F6
#define SEQ_MUTEA KC_F7
#define SEQ_MUTEB KC_F8
#define SEQ_PAGE KC_F9
#define SEQ_PLAYSTOP KC_SPACE
#define SEQ_SEL KC_F10
#define SEQ_VEL KC_F11
#endif
