#!/usr/bin/env python
import colorsys

output = ""

with open('keymap.c', 'r') as fh:
  for l in fh.readlines():
    if l.startswith('#define COLOR_'):
      if '_RGB' in l:
        # autogenerated line, just skip it
        continue
      # now we have our customer
      output += (l)
      define, defname, rest = l.split(' ', 2)
      h, s, v = [float(a) / 255.0 for a in rest.replace(' ', '').split(',')]
      r, g, b = [round(a * 255) for a in colorsys.hsv_to_rgb(h, s, v)]
      
      output += f"#define {defname}_RGB {r},{g},{b}\n"
    else:
      output += l
print(output.rstrip('\n'))
